apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:peawdev/k8s-argocd.git
    targetRevision: main
    path: app-of-app/name-app/nonprod/app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true