apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-chart-api-app-uat
  namespace: argocd
spec:
  project: default
  source:
    path: ./
    repoURL: git@github.com:peawdev/k8s-calculator-nonprd.git
    targetRevision: main
    helm:
      releaseName: app-chart-api-app-uat
      valueFiles:
        - ./values/uat.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    automated:
      prune: true