apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-chart-api-app
  namespace: argocd
spec:
  project: default
  source:
    path: ./
    repoURL: git@github.com:peawdev/k8s-calculator-nonprd.git
    targetRevision: develop
    helm:
      releaseName: app-chart-api-app
      valueFiles:
        - ./values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app-chart-api-app
  syncPolicy:
    automated:
      prune: true