apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-nonprd-dev
  namespace: argocd
spec:
  project: default
  source:
    path: ./
    repoURL: git@github.com:peawdev/k8s-calculator-nonprd.git
    targetRevision: dev
    helm:
      releaseName: calculator-nonprd-dev
      valueFiles:
        - ./values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: calculator-nonprd-dev
  syncPolicy:
    automated:
      prune: true